WebApplication/Models/Image.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace WebApplication.Models
{
    public class Image
    {
        [Key]
        public int Id { get; set; }
        public string Name { get; set; }

        public string Author_Id { get; set; }

        [ForeignKey("Author_Id")]
        public virtual ApplicationUser Author { get; set; }
    }
}

WebApplication/Controllers/ImagesController.cs
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using WebApplication.Extensions;
using WebApplication.Models;

namespace WebApplication.Controllers
{
    public class ImagesController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Images
        public ActionResult Index()
        {
            var images = db.Images.ToList();
            return View(images);
        }

        // GET: Images/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Image image = db.Images.Find(id);
            if (image == null)
            {
                return HttpNotFound();
            }
            return View(image);
        }

        // GET: Images/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Images/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        
        public ActionResult Create([Bind(Include = "Id")] Image image, HttpPostedFileBase file)
        {
            if (User.Identity.IsAuthenticated)
            {
                if (file.ContentLength > 0)
                {
                    foreach (var img in db.Images.ToList())
                    {
                        if (img.Name == file.FileName)
                        {
                            this.AddNotification("Изображението вече го има!", NotificationType.WARNING);
                            return RedirectToAction("Index");
                        }
                    }
                    var fileName = Path.GetFileName(file.FileName);
                    var path = Path.Combine(Server.MapPath("~/Gallery/"), fileName);
                    file.SaveAs(path);
                    
                    image.Name = fileName;
                    image.Author = db.Users.Single(u => u.UserName == User.Identity.Name);
                    db.Users.Find(image.Author.Id).Images.Add(image);
                    db.Images.Add(image);
                    db.SaveChanges();
                    this.AddNotification("Успешно качихте изображението.", NotificationType.SUCCESS);
                    return RedirectToAction("Index");

                }
                this.AddNotification("Грешка! Файлът не се качи.", NotificationType.ERROR);
            }

            this.AddNotification("Първо трябва да се впишете с потребителски профил.", NotificationType.WARNING);
            return RedirectToAction("Index");
           
        }


        // GET: Images/Edit/5
       
        // GET: Images/Delete/5
        [Authorize]
        public ActionResult Delete(int? id)
        {
            var currentUser = db.Users.FirstOrDefault(u => u.UserName == User.Identity.Name);
            var currentImage = db.Images.Find(id);

            if(currentImage.Author.UserName == User.Identity.Name ||
                currentUser.Role == "Admin")
            {
                if (id == null)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }
                Image image = db.Images.Find(id);
                if (image == null)
                {
                    return HttpNotFound();
                }
                return View(image);
            }
            return RedirectToAction("Index");
        }

        // POST: Images/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {

            
            var image = db.Images.Find(id);
            if(image != null)
            {
                db.Images.Remove(image);
                db.Users.FirstOrDefault(u => u.UserName == User.Identity.Name).Images.Remove(image);
                db.SaveChanges();
                this.AddNotification("Изображението е изтрито.", NotificationType.INFO);
                return RedirectToAction("Index");
            }
            this.AddNotification("Грешка! Изображението не съществува!", NotificationType.ERROR);
            return RedirectToAction("Index");
        }

        public FileResult Download(string ImageName)
        {
            return File("~/Gallery/" + ImageName, System.Net.Mime.MediaTypeNames.Application.Octet);

        }
        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

WebApplication/Views/Images/Delete.cshtml
@model WebApplication.Models.Image

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Image</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

WebApplication/Views/Images/Details.cshtml
@model WebApplication.Models.Image

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Image</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Path)
        </dt>

        <dd>
            <img src="@Model.Path" />
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

WebApplication/Views/Images/Index.cshtml
@model IEnumerable<WebApplication.Models.Image>

@{
    ViewBag.Title = "Index";
    List <WebApplication.Models.ApplicationUser> users = ViewBag.Users;
    WebApplication.Models.ApplicationUser currentUser = users.FirstOrDefault(u => u.UserName == User.Identity.Name);
}

@using (Html.BeginForm("Create", "Images", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    <div class="img-upload">
        <h2>Качи снимка</h2>
        <input type="file" id="file" name="file" />
        <input type="submit" value="Качи"  />
    </div>
   
}
<table class="table">
    <tr>
        <th>
            @Html.DisplayName("Име")
        </th>
       <th></th>
        <th>
            @Html.DisplayName("Автор")
        </th>
    </tr>

@foreach (var image in Model) {
    <tr>
        <td>
            @Html.ActionLink(image.Name, "Download", "Images", new { ImageName = image.Name }, null)
        </td>
        <td>
            @{
                var path = "~/Gallery/" + image.Name;
                <img src="@Url.Content(path)" alt="Image" width="300" />
            }
       
        </td>
        <td>
            @image.Author.UserName
        </td>
        <td>
            @if (User.Identity.IsAuthenticated)
            {
                if (image.Author.UserName == User.Identity.Name ||
                currentUser.Role == "Admin")
                {

                    @Html.ActionLink("Изтрий", "Delete", new { id = image.Id })
                }
            }
        </td>
    </tr>
}

</table>