WebApplication/Controllers/PostsController.cs
using System;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using WebApplication.Extensions;
using WebApplication.Models;

namespace WebApplication.Controllers
{
    public class PostsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Posts
        public ActionResult Index()
        {
          
            var postsWithAuthors = db.Posts.
                Include(p => p.Author).ToList(); 
            return View(postsWithAuthors.OrderByDescending(p => p.Date).ToList());
        }

        // GET: Posts/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Post post = db.Posts.Find(id);
            if (post == null)
            {
                return HttpNotFound();
            }
            
            return View(post);
        }

        // GET: Posts/Create
        [Authorize]
        public ActionResult Create()
        {
            ViewBag.Tags = db.Tags.ToList();
            ViewBag.Categories = db.Categories.ToList();
            return View();
        }

        // POST: Posts/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [ValidateInput(false)]
        [Authorize]
        public ActionResult Create([Bind(Include = "Id,Title,Body,Date,Author_Id")] Post post,
            string category,  string [] tags, HttpPostedFileBase file)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    if (file.ContentLength > 0)
                    {
                        var fileName = Path.GetFileName(file.FileName);
                        var path = Path.Combine(Server.MapPath("~/Files/"), fileName);
                        file.SaveAs(path);
                        post.FileName = fileName;
                    }
                    ViewBag.Message = "Upload successful";

                }
                catch
                {
                    ViewBag.Message = "Upload failed";

                }
               
                post.Author = db.Users.FirstOrDefault(u => u.UserName == User.Identity.Name);
                post.CommentsCount = 0;
                post.Date = DateTime.Now;
                
                if(tags != null)
                {
                    foreach (var tagId in tags)
                    {
                        var id = Convert.ToInt32(tagId);
                        var tag = db.Tags.Find(id);
                        post.Tags.Add(tag);
                        db.Tags.Find(id).Posts.Add(post);
                    }
                }
                var categoryId = Convert.ToInt32(category);
                var postCategory = db.Categories.Find(categoryId);
                post.Category = postCategory;

                db.Users.Find(post.Author.Id).Posts.Add(post);
                foreach (var userPost in db.Users.Find(post.Author.Id).Posts)
                {
                    var p = userPost;
                }
                db.Categories.Find(categoryId).Posts.Add(post);
                db.Posts.Add(post);
                db.SaveChanges();
                this.AddNotification("Статията е успешно създадена.", NotificationType.SUCCESS);
                return RedirectToAction("Index");
            }
            this.AddNotification("Грешка! Някое от полетата не е попълнено.", NotificationType.ERROR);
            return RedirectToAction("/Create");
        }

        // GET: Posts/Edit/5
        [Authorize]
        public ActionResult Edit(int? id)
        {
            var currentPost = db.Posts.Single(p => p.Id == id);
            var currentUser = db.Users.FirstOrDefault(u => u.UserName == User.Identity.Name);

            if (User.Identity.Name == currentPost.Author.UserName || 
               currentUser.Role == "Admin")
            {
                if (id == null)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }
                Post post = db.Posts.Find(id);
                if (post == null)
                {
                    return HttpNotFound();
                }
                return View(post);
            }
            return RedirectToAction("Index");
        }

        // POST: Posts/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [ValidateInput(false)]
        [Authorize]
        public ActionResult Edit( Post post, string Title, string Body, int? id)
        {
            if (ModelState.IsValid)
            {
                post = db.Posts.Find(id);
                post.Title = Title;
                post.Body = Body;
                db.Entry(post).State = EntityState.Modified;
                db.SaveChanges();
                this.AddNotification("Статията е успешно редактирана.", NotificationType.SUCCESS);
                return RedirectToAction("Index");
            }
            this.AddNotification("Грешка! Някое от полетата не е попълнено коректно.", NotificationType.ERROR);
            return RedirectToAction("/Edit/" + id);
        }

        // GET: Posts/Delete/5
        [Authorize]
        public ActionResult Delete(int? id)
        {
            var currentPost = db.Posts.Single(p => p.Id == id);
            var currentUser = db.Users.FirstOrDefault(u => u.UserName == User.Identity.Name);

            if (User.Identity.Name == currentPost.Author.UserName ||
               currentUser.Role == "Admin")
            {
                if (id == null)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }
                Post post = db.Posts.Find(id);
                if (post == null)
                {
                    return HttpNotFound();
                }
                return View(post);
            }
            return RedirectToAction("Index");
        }

        // POST: Posts/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize]
        public ActionResult DeleteConfirmed(int id)
        {
            Post post = db.Posts.Find(id);
            foreach (Comment comment in post.Comments.ToList())
            {
                db.Comments.Remove(comment);
            }
            foreach (var tag in post.Tags.ToList())
            {
                var tagId = tag.Id;
                db.Tags.Find(tagId).Posts.Remove(post);
            }
            db.Users.Find(post.Author.Id).Posts.Remove(post);
            db.Posts.Remove(post);
            db.SaveChanges();
            this.AddNotification("Статията е изтрита.", NotificationType.INFO);
            return RedirectToAction("Index");
        }
        public FileResult Download(string ImageName)
        {
            return File("~/Files/" + ImageName, System.Net.Mime.MediaTypeNames.Application.Octet, ImageName);

        }
        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

WebApplication/Controllers/TagsController.cs
using System;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using WebApplication.Extensions;
using WebApplication.Models;

namespace WebApplication.Controllers
{
    public class TagsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

       
        // GET: Tags
        public ActionResult Index()
        {
            return View(db.Tags.ToList());
        }

        // GET: Tags/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Tag tag = db.Tags.Find(id);
            if (tag == null)
            {
                return HttpNotFound();
            }
            return View(tag);
        }

        // GET: Tags/Create
       
        public ActionResult Create()
        {
           
            var currentUser = db.Users.FirstOrDefault(u => u.UserName == User.Identity.Name);

            if (User.Identity.IsAuthenticated && 
               currentUser.Role == "Admin")
            {
                ViewBag.Posts = db.Posts.ToList();
                return View();
            }
            return RedirectToAction("../");
        }

        // POST: Tags/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
       
        public ActionResult Create([Bind(Include = "Id,Name")] Tag tag, string [] post)
        {
          
            if (ModelState.IsValid)
            {
                if(post != null)
                {
                    foreach (var p in post)
                    {
                        var id = Convert.ToInt32(p);
                        tag.Posts.Add(db.Posts.Single(x => x.Id == id));

                        db.Posts.Find(id).Tags.Add(tag);
                    }
                }
               
                db.Tags.Add(tag);
                db.SaveChanges();
                this.AddNotification("Тагът е създаден.", NotificationType.SUCCESS);
                return RedirectToAction("/Details/"+ tag.Id);
            }
            this.AddNotification("Грешка. Тагът не се създаде!", NotificationType.ERROR);
            return View(tag);
        }

        // GET: Tags/Edit/5
       
        public ActionResult Edit(int? id)
        {
            var currentUser = db.Users.FirstOrDefault(u => u.UserName == User.Identity.Name);

            if (User.Identity.IsAuthenticated &&
               currentUser.Role == "Admin")
            {
                if (id == null)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }
                ViewBag.Posts = db.Posts.ToList();
                Tag tag = db.Tags.Find(id);
                if (tag == null)
                {
                    return HttpNotFound();
                }
                return View(tag);
            }
            return RedirectToAction("../");
        }

        // POST: Tags/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
       
        public ActionResult Edit(string name, string [] post, int? id)
        {
            if (ModelState.IsValid)
            {
                var oldTag = db.Tags.Find(id);
                foreach (var p in oldTag.Posts.ToList())
                {
                    db.Posts.Find(p.Id).Tags.Remove(oldTag);
                    oldTag.Posts.Remove(p);
                    
                }
                var newTag = oldTag;
                newTag.Name = name;
                if (post != null)
                {
                    foreach (var p in post)
                    {
                        var postId = Convert.ToInt32(p);
                        newTag.Posts.Add(db.Posts.Single(x => x.Id == postId));

                        db.Posts.Find(postId).Tags.Add(newTag);
                    }
                }
                db.Entry(newTag).State = EntityState.Modified;
                db.SaveChanges();
                this.AddNotification("Тагът е редактиран", NotificationType.SUCCESS);
                return RedirectToAction("Index");
            }
            this.AddNotification("Грешка!", NotificationType.ERROR);
            return View();
        }

        // GET: Tags/Delete/5
       
        public ActionResult Delete(int? id)
        {
            var currentUser = db.Users.FirstOrDefault(u => u.UserName == User.Identity.Name);

            if (User.Identity.IsAuthenticated &&
               currentUser.Role == "Admin")
            {
                if (id == null)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }
                Tag tag = db.Tags.Find(id);
                if (tag == null)
                {
                    return HttpNotFound();
                }
                return View(tag);
            }
            return RedirectToAction("../");
        }

        // POST: Tags/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
      
        public ActionResult DeleteConfirmed(int id)
        {
            
            Tag tag = db.Tags.Find(id);
            foreach (var post in tag.Posts.ToList())
            {
                var postId = post.Id;
                db.Posts.Find(postId).Tags.Remove(tag);
            }
            db.Tags.Remove(tag);
            db.SaveChanges();
            this.AddNotification("Тагът е изтрит!", NotificationType.SUCCESS);
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
        
    }
}

WebApplication/Controllers/UsersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebApplication.Models;

namespace WebApplication.Controllers
{
    public class UsersController : Controller
    {
        ApplicationDbContext db = new ApplicationDbContext();
        public ActionResult Index()
        {
            var users = db.Users.ToList();
            return View(users);
        }
    }
}

WebApplication/Views/Shared/_Layout.cshtml
@{
    List<WebApplication.Models.ApplicationUser> users = ViewBag.Users;
}
﻿<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Blog</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>

    <div class="navbar navbar-inverse">

        <div class="container">
            <div class="navbar-header">
                <img class="img-rounded " style="margin-top:3px" width="50" height="45" src="~/Img/monkey-clipart-black-and-white-16981-monkey-face-svg.png" />
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Mighty Monkeys Blog", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })

            </div>

            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Начало", "Index", "Home")</li>
                    <li>@Html.ActionLink("Статии", "Index", "Posts")</li>
                    @if (User.Identity.IsAuthenticated)
                    {
                        <li>@Html.ActionLink("Нова статия", "Create", "Posts")</li>
                    }

                    @if (User.Identity.IsAuthenticated &&
                users.FirstOrDefault(u => u.UserName == User.Identity.Name).Role == "Admin")
                    {
                        <li>@Html.ActionLink("Тагове", "Index", "Tags")</li>
                        <li>@Html.ActionLink("Нов таг", "Create", "Tags")</li>
                        <li>@Html.ActionLink("Нова категория", "Create", "Categories")</li>
                        <li>@Html.ActionLink("Категории", "Index", "Categories")</li>
                    }

                    <li>@Html.ActionLink("Галерия", "Index", "Images")</li>
                    <li>@Html.ActionLink("Потребители", "Index", "Users")</li>
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @Html.Partial("_Notifications")
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Created By Mighty Monkeys</p>
        </footer>
    </div>
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

WebApplication/Views/Shared/_Notifications.cshtml
@using WebApplication.Extensions

@{
    var errorList = Html.GetNotifications(NotificationType.ERROR);
    var warningList = Html.GetNotifications(NotificationType.WARNING);
    var successList = Html.GetNotifications(NotificationType.SUCCESS);
    var infoList = Html.GetNotifications(NotificationType.INFO);
}
<!-- display errors -->
@if (errorList != null)
{
    <div class="alert alert-danger alert-dismissable">
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
        @if(errorList.Count() > 1){
            <strong><span class="glyphicon glyphicon-remove"></span> There are @errorList.Count() errors: </strong>
            <ul>
                @foreach (String message in errorList)
                {
                    <li>@Html.Raw(message)</li>
                }
            </ul>
        }
        else{
            <strong><span class="glyphicon glyphicon-remove"></span> Error: </strong>
            @Html.Raw(errorList.First())
        }
    </div>
}

<!-- display warnings -->
@if (warningList != null)
{
    <div class="alert alert-warning alert-dismissable">
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
        @if(warningList.Count() > 1){
            <strong><span class="glyphicon glyphicon-warning-sign"></span> There are @warningList.Count() warnings: </strong>
            <ul>
                @foreach (String message in warningList)
                {
                    <li>@Html.Raw(message)</li>
                }
            </ul>
        }
        else{
            <strong><span class="glyphicon glyphicon-warning-sign"></span> Warning: </strong>
            @Html.Raw(warningList.First())
        }
    </div>
}

<!-- display success -->
@if (successList != null)
{
    <div class="alert alert-success alert-dismissable">
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
        @if(successList.Count() > 1){
            <strong><span class="glyphicon glyphicon-ok"></span> There are @successList.Count() successful notifications: </strong>
            <ul>
                @foreach (String message in successList)
                {
                    <li>@Html.Raw(message)</li>
                }
            </ul>
        }
        else{
            <strong><span class="glyphicon glyphicon-ok"></span> Success! </strong>
            @Html.Raw(successList.First())
        }
    </div>
}

<!-- display success -->
@if (infoList != null)
{
    <div class="alert alert-info alert-dismissable">
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
        @if(infoList.Count() > 1){
            <strong><span class="glyphicon glyphicon-info-sign"></span> There are @infoList.Count() notifications: </strong>
            <ul>
                @foreach (String message in infoList)
                {
                    <li>@Html.Raw(message)</li>
                }
            </ul>
        }
        else{
            <strong><span class="glyphicon glyphicon-info-sign"></span> </strong>
            @Html.Raw(infoList.First())
        }
    </div>
}